### ISSUE TITLE
setTargetPath 没有生效

### ISSUE THREAD

**Issue by sparksunflower** [ZLYang110/FileSelector#11]
配置FileSelector时，setTargetPath设置了目录，但打开的仍然是root目录

FileSelector.from(this)
                .onlyShowFolder()  //只显示文件夹
                .onlySelectFolder()  //只能选择文件夹
                .isSingle() // 只能选择一个
                .setSortType(FileSelector.BY_TIME_ASC) //设置时间排序
                .requestCode(999) //设置返回码
                .setTargetPath("/storage/emulated/0/Android/")
                .start();

**Comment by ZLYang110** [comment]
已更新
