### ISSUE TITLE
库里标题颜色可以固定吗

### ISSUE THREAD

**Issue by ChangKaiKing** [ZLYang110/FileSelector#5]
我加到项目里显示标题颜色是透明的，文字是白色的，看着很费劲，请问您这边库里可以固定一个颜色吗

**Comment by ZLYang110** [comment]
标题颜色默认是你自己项目中 colorPrimary颜色。我现在更新一版，可以自定义标题颜色和标题文字颜色，方便你使用。

**Comment by ZLYang110** [comment]
感谢反馈，我已经修改了一版，你可以自行设置颜色值，具体参考redme。引入最新的库就可使用~~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLYang110/FileSelector"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月20日(星期六) 下午2:14
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ZLYang110/FileSelector] 库里标题颜色可以固定吗 (#5)





 
我加到项目里显示标题颜色是透明的，文字是白色的，看着很费劲，请问您这边库里可以固定一个颜色吗
