### ISSUE TITLE
不适配Android11 

### ISSUE THREAD

**Issue by baijianghai** [ZLYang110/FileSelector#9]
Android 11 加载不出来文档

**Comment by ZLYang110** [comment]
我在真机和模拟机测试都是可以的。你告诉我你什么设备，我能找到了我试一下。
![image](https://user-images.githubusercontent.com/17540057/122145674-45643000-ce88-11eb-8692-a6b12be0a60f.png)

**Comment by ZLYang110** [comment]
我在真机和模拟机测试都是可以的。你告诉我你什么设备型号，我能找到了我试一下。

**Comment by baijianghai** [comment]
红米11读不到文件夹信息 全是加载中，通过路径new file的形式调取不到子目录的信息，官方推荐直接用文件才能读取发自我的荣耀手机-------- 原始邮件 --------发件人： ZLYang ***@***.***>日期： 2021年6月16日周三 09:51收件人： ZLYang110/FileSelector ***@***.***>抄送： 白鹏 ***@***.***>, Author ***@***.***>主    题： Re: [ZLYang110/FileSelector] 不适配Android11  (#9)

我在真机和模拟机测试都是可以的。你告诉我你什么设备，我能找到了我试一下。
